### ISSUE TITLE
Can't create folders or upload images. Get redirected to account creation.

### ISSUE THREAD

**Issue by nicxvan** [linuxserver/docker-photoshow#22]
Ubuntu 18.04
There are no logs for either php, nginx, or docker.

**Comment by aptalca** [comment]
Post the command you used to create the container as well as a docker log

**Comment by nlighteneddesign** [comment]
I'm using docker-compose

```
photoshow:
    image: linuxserver/photoshow
    container_name: photoshow
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /srv/docker/photoshow/config:/config
      - /srv/docker/photoshow/pictures:/Pictures:ro
      - /srv/docker/photoshow/thumbs:/Thumbs
    ports:
      - 4444:80
    restart: unless-stopped
```

And here are the logs:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 10-adduser: executing... ,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
We gratefully accept donations at:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    1000,
User gid:    1000,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 20-config: executing... ,
[cont-init.d] 20-config: exited 0.,
[cont-init.d] 30-keygen: executing... ,
generating self-signed keys in /config/keys, you can replace these with your own keys if required,
Generating a RSA private key,
..........+++++,
.............................+++++,
writing new private key to '/config/keys/cert.key',
-----,
[cont-init.d] 30-keygen: exited 0.,
[cont-init.d] 40-install: executing... ,
fetching photoshow files from github,
Cloning into '/config/www/PhotoShow'...,
Note: checking out '48aabb98'.,
,
You are in 'detached HEAD' state. You can look around, make experimental,
changes and commit them, and you can discard any commits you make in this,
state without impacting any branches by performing another checkout.,
,
If you want to create a new branch to retain commits you create, you may,
do so (now or later) by using -b with the checkout command again. Example:,
,
  git checkout -b <new-branch-name>,
,
HEAD is now at 48aabb9 Merge pull request #368 from kosli/patch-1,
[cont-init.d] 40-install: exited 0.,
[cont-init.d] 99-custom-files: executing... ,
[custom-init] no custom files found exiting...,
[cont-init.d] 99-custom-files: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,```
